### ISSUE TITLE
Can't build viewer

### ISSUE THREAD

**Issue by greg-cacheq** [eggachecat/react-jycm-viewer#1]
When I run 'yarn start' or 'yarn build' I get the following error:

yarn run v1.22.10
$ webpack --config config/webpack.prod.config.js
[webpack-cli] Error: Cannot find module 'vs/editor/editor.worker'

**Comment by eggachecat** [comment]
@greg-cacheq hi Have you installed [monaco-editor](https://github.com/microsoft/monaco-editor)? 
P.S. A new version will be released soon. It will be much more useable

**Comment by greg-cacheq** [comment]
Worked once I installed monaco-editor, and updated the package.json to be:

"monaco-editor-webpack-plugin": "^7.0.1",
