### ISSUE TITLE
Update README with example of using the viewer

### ISSUE THREAD

**Issue by greg-cacheq** [eggachecat/react-jycm-viewer#2]
The viewer works out of the box with a hard-coded example. There are no instructions with how to launch it by passing in 2 json files and the results of jycm diff to view things graphically.

**Comment by eggachecat** [comment]
@greg-cacheq okay！I will update it soon!

**Comment by eggachecat** [comment]
@greg-cacheq Hi I just updated the readme and release a version on npm. And here comes a example project https://github.com/eggachecat/react-jycm-viewer-example!
